### ISSUE TITLE
[Error] Error When Running Command

### ISSUE THREAD

**Issue by George-Seven** [cryptax/droidlysis#9] opened 2021-11-09 07:26 UTC
As per instruction in github, installed Droidlysis and setup paths.

When running command :-

`sudo python3 ./droidlysis3.py --input ~/softs/smshandler.apk --output ~/softs/tmp`

There is error log,

`Processing: /root/softs/smshandler.apk ...`
`Filename: /root/softs/smshandler.apk`
`Traceback (most recent call last):`
`  File "./droidlysis3.py", line 144, in <module>
    process_input(args)`
`  File "./droidlysis3.py", line 78, in process_input
    process_file(os.path.join('.',element), args.output, args.verbose, args.clearoutput, args.enable_procyon, args.disable_report, args.silent, args.no_kit_exception)`
`  File "./droidlysis3.py", line 92, in process_file
    sample = droidsample.droidsample(infile, outdir, verbose, clear, enable_procyon, disable_report, silent, no_kit_exception)`
`  File "/root/softs/droidlysis/droidsample.py", line 51, in __init__
    verbose=self.verbose)`
`  File "/root/softs/droidlysis/droidproperties.py", line 53, in __init__
    self.clear_fields()`
`  File "/root/softs/droidlysis/droidproperties.py", line 97, in clear_fields
    self.smaliconfig = droidconfig.droidconfig(droidconfig.SMALI_CONFIGFILE, self.verbose)`
`  File "/root/softs/droidlysis/droidconfig.py", line 25, in __init__
    assert os.access(filename, os.R_OK) != False, "File {0} is not readable".format(filename)
AssertionError: File ~/./conf/smali.conf is not readable`

Can you help, what should I do.

Below is the smali.conf permission manager, didn't touch it :-
![Image](https://user-images.githubusercontent.com/92206927/140880981-3c9ced7b-80a1-4d71-8245-6e379bc44be0.jpeg)

**Comment by cryptax** [comment] 2021-11-12 08:00
that's quite strange, I can't reproduce it. What OS do you have? Do you really have a valid smali.conf file?

**Comment by George-Seven** [comment] 2021-11-15 06:39
Ahaha 😅, the OS is not using PC, I'm using Linux Deploy app to run chroot xfce in Android 10.

Being able use droidlysis to analyse in the phone would be awesome and this was the only error I couldn't resolve.

**Comment by cryptax** [comment] 2023-02-21 10:53
I'm closing this as I have no update.

**Closed by cryptax** 2023-02-21 10:53 UTC
